// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/generate-types.mjs
// Run `npm run generate:types` to regenerate

export enum TileColor {
  RED = 'red',
  BLUE = 'blue',
  YELLOW = 'yellow',
  BLACK = 'black',
}

export enum CombinationType {
  RUN = 'run',
  GROUP = 'group',
}

export interface Tile {
  id: string;
  number: number;
  color: TileColor | null;
  isJoker: boolean;
}

export interface Combination {
  id: string;
  tiles: Tile[];
  type: CombinationType;
}

export interface PlayerPublicInfo {
  id: string;
  nickname: string;
  isReady: boolean;
  isHost: boolean;
  tileCount: number;
  hasInitialMeld: boolean;
  score: number;
}

export interface GameState {
  roomCode: string;
  players: PlayerPublicInfo[];
  currentPlayerId: string | null;
  board: Combination[];
  deckCount: number;
  gameStarted: boolean;
  gameOver: boolean;
  winner: PlayerPublicInfo | null;
  placedThisTurn: boolean;
  drewTileThisTurn: boolean;
}

export interface CreateRoomDto {
  nickname: string;
}

export interface JoinRoomDto {
  roomCode: string;
  nickname: string;
}

export interface PlayerActionDto {
  roomCode: string;
}

export interface PlaceCombinationDto extends PlayerActionDto {
  combination: { tiles: Tile[]; type: CombinationType };
}

export interface PlaceMultipleCombinationsDto extends PlayerActionDto {
  combinations: { tiles: Tile[]; type: CombinationType }[];
}

export interface SubmitBoardStateDto extends PlayerActionDto {
  combinations: { tiles: Tile[] }[];
}

export interface RejoinRoomDto {
  roomCode: string;
  playerId: string;
}

export const GAME_CONSTANTS = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 4,
  INITIAL_TILES_PER_PLAYER: 14,
  MIN_INITIAL_MELD_VALUE: 30,
  MIN_COMBINATION_SIZE: 3,
  MAX_TILE_NUMBER: 13,
  JOKER_COUNT: 2,
  TILES_PER_SET: 2,
  ROOM_CODE_LENGTH: 6,
} as const;

export const TILE_COLORS = ['red', 'blue', 'yellow', 'black'] as const;

// Socket Event Payloads (Server -> Client)

export interface RoomCreatedPayload {
  roomCode: string;
  player: PlayerPublicInfo;
}

export interface JoinedRoomPayload {
  roomCode: string;
  players: PlayerPublicInfo[];
  myPlayerId: string;
  isHost: boolean;
}

export interface RoomFoundPayload {
  roomCode: string;
  players: PlayerPublicInfo[];
  gameStarted: boolean;
  maxPlayers: number;
}

export interface PlayerJoinedPayload {
  players: PlayerPublicInfo[];
  newPlayer: PlayerPublicInfo;
}

export interface PlayerLeftPayload {
  players: PlayerPublicInfo[];
  leftPlayer: string;
}

export interface PlayerStatusChangedPayload {
  players: PlayerPublicInfo[];
}

export interface GameStartedPayload {
  gameState: GameState;
  myTiles: Tile[];
  isMyTurn: boolean;
}

export interface TileDrawnPayload {
  myTiles: Tile[];
  deckCount: number;
}

export interface BoardUpdatedPayload {
  gameState: GameState;
}

export interface MyTilesUpdatedPayload {
  tiles: Tile[];
}

export interface TurnChangedPayload {
  gameState: GameState;
  currentPlayerId: string;
}

export interface YourTurnPayload {
  isMyTurn: boolean;
}

export interface DeckUpdatedPayload {
  deckCount: number;
}

export interface GameOverPayload {
  winner: PlayerPublicInfo;
  gameState: GameState;
}

export interface ErrorPayload {
  message: string;
}
